#!/bin/bash


function ionosphere ()
{
	cp ionosphere.data ios
	# wc ios

	# remove attribute 2: only zeros
	cat ios | cut -d',' -f 1,3- > ios-2

	# bad  class: 0
	# good class: 1
	cat ios-2 | sed 's/b/0/g' | sed 's/g/1/g' > ios.classes

	# train data: first 157 items

	head -n 157 ios.classes > ios.train 

	# test data: next 158 items

	tail -n 158 ios.classes > ios.test
}


function haberman ()
{
	cp haberman.data hab
	
	# wc hab
  
   head -n 153 hab > hab.train
   tail -n 153 hab > hab.test

}


haberman 

